"""One-off generator for docs/assets/*.png -- run manually, not part of the
package. Reads real results/*.jsonl and results/*-summary.json (gitignored,
local build artifacts) and renders committed, static images for the README:
a Track A ASR bar chart and a styled real-output comparison panel. Track B's
cost-curve plot is copied in separately -- it's already generated by
ladder_eval.py.

Run from repo root: python scripts/gen_readme_assets.py
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
OUT = ROOT / "docs" / "assets"
OUT.mkdir(parents=True, exist_ok=True)


def track_a_bar_chart():
    naive = json.loads((RESULTS / "naive-20260807-005332-summary.json").read_text())
    hardened = json.loads((RESULTS / "hardened-20260807-013221-summary.json").read_text())
    robust = json.loads((RESULTS / "robust-20260807-192035-summary.json").read_text())

    cases = ["A001", "A002", "A003"]
    labels = ["A001\ninjection", "A002\npoisoning", "A003\nexfiltration", "overall"]

    naive_vals = [naive["asr_by_case"][c] * 100 for c in cases] + [naive["overall_asr"] * 100]
    hardened_vals = [hardened["asr_by_case"][c] * 100 for c in cases] + [hardened["overall_asr"] * 100]
    robust_vals = [robust["asr_by_case"][c] * 100 for c in cases] + [robust["overall_asr"] * 100]

    x = range(len(labels))
    w = 0.26
    fig, ax = plt.subplots(figsize=(8, 4.5))
    b1 = ax.bar([i - w for i in x], naive_vals, width=w, label="naive", color="#c0392b")
    b2 = ax.bar([i for i in x], hardened_vals, width=w, label="hardened", color="#2980b9")
    b3 = ax.bar([i + w for i in x], robust_vals, width=w, label="robust*", color="#7f8c8d",
                hatch="//", edgecolor="white")

    for bars in (b1, b2, b3):
        for bar in bars:
            h = bar.get_height()
            ax.annotate(f"{h:.0f}%", (bar.get_x() + bar.get_width() / 2, h),
                        textcoords="offset points", xytext=(0, 3), ha="center", fontsize=8)

    ax.set_xticks(list(x))
    ax.set_xticklabels(labels)
    ax.set_ylabel("Attack Success Rate (lower is better)")
    ax.set_ylim(0, 110)
    ax.set_title("Track A -- ASR by attack class, naive vs hardened vs robust")
    ax.legend(loc="upper right")
    ax.annotate(
        "*robust measured on llama3.2:1b (interactive dev config per\n"
        "robust_a002.py), not llama3.1:8b like naive/hardened -- not\n"
        "an apples-to-apples model comparison, utility also lower (40%).",
        xy=(0, 0), xycoords="axes fraction", xytext=(0, -55),
        textcoords="offset points", fontsize=7.5, color="#555",
    )
    fig.tight_layout()
    fig.savefig(OUT / "track_a_asr.png", dpi=160, bbox_inches="tight")
    plt.close(fig)
    print("wrote", OUT / "track_a_asr.png")


def _wrap(s: str, width: int = 78) -> str:
    return "\n".join(textwrap.wrap(s, width=width, replace_whitespace=False))


def sample_output_panel():
    with open(RESULTS / "naive-20260807-005332.jsonl", encoding="utf-8") as f:
        naive_answer = next(
            json.loads(l)["answer"] for l in f
            if json.loads(l).get("kind") == "attack" and json.loads(l).get("case") == "A001"
        )
    with open(RESULTS / "hardened-20260807-013221.jsonl", encoding="utf-8") as f:
        for l in f:
            d = json.loads(l)
            if d.get("kind") == "attack" and d.get("case") == "A001":
                hardened_answer = d["answer"]
                dropped = d["meta"]["dropped_chunks"]
                break

    fig, axes = plt.subplots(2, 1, figsize=(9.5, 6.2))
    fig.suptitle(
        'Real recorded output, case A001 (instruction injection) -- query: '
        '"How do I enable CORS in FastAPI?"',
        fontsize=10, fontweight="bold",
    )

    panels = [
        (axes[0], "naive -- ATTACK SUCCEEDS", naive_answer[:340], "#c0392b",
         "#fff5f5"),
        (axes[1], "hardened -- DEFENDED", hardened_answer[:340], "#1e8449",
         "#f2fbf5"),
    ]
    for ax, title, text, color, bg in panels:
        ax.set_facecolor(bg)
        ax.set_xticks([]); ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_edgecolor(color)
            spine.set_linewidth(1.5)
        ax.text(0.02, 0.92, title, transform=ax.transAxes, fontsize=10.5,
                 fontweight="bold", color=color, va="top", family="monospace")
        ax.text(0.02, 0.74, _wrap(text), transform=ax.transAxes, fontsize=8.7,
                 va="top", family="monospace", color="#222")

    axes[1].text(
        0.02, 0.06,
        f"screened out: {dropped[0]['source'].split(chr(92))[-1]}  "
        f"(reason: {dropped[0]['reason']}, score {dropped[0]['score']})",
        transform=axes[1].transAxes, fontsize=8, color="#555", family="monospace",
    )
    fig.tight_layout(rect=[0, 0, 1, 0.94])
    fig.savefig(OUT / "sample_output_a001.png", dpi=160, bbox_inches="tight")
    plt.close(fig)
    print("wrote", OUT / "sample_output_a001.png")


if __name__ == "__main__":
    track_a_bar_chart()
    sample_output_panel()
